#!/bin/sh
### BEGIN INIT INFO
# Provides:          ipset-persistent
# Required-Start:    mountkernfs $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Start-Before:    $network netfilter-persistent
# X-Stop-After:      $network netfilter-persistent
# Short-Description: Load boot-time ipset rules
# Description:       Loads/saves current ipset rules from/to /etc/iptables
#  to provide a persistent rule set during boot time
### END INIT INFO

. /lib/lsb/init-functions

# return code
declare -i rc="0"

IPSET="/sbin/ipset"

load_rules() {
	if [ ! -x $IPSET ]; then
		log_action_cont_msg " skipping ipset-persistent ($IPSET not exist)"
	else
		log_action_begin_msg "Loading ipset rules"
		if [ ! -f /etc/iptables/ipset ]; then
			log_action_cont_msg " skipping ipset-persistent (no rules to load)"
		else
			log_action_cont_msg " ipset"
			$IPSET destroy
			$IPSET restore < /etc/iptables/ipset 2> /dev/null
			if [ $? -ne 0 ]; then
				rc="1"
			fi
		fi
	fi

	log_action_end_msg $rc
}

save_rules() {
	if [ ! -x $IPSET ]; then
		log_action_cont_msg " $IPSET not exist"
	else
		log_action_begin_msg "Saving rules"
		log_action_cont_msg " ipset"
		$IPSET save > /etc/iptables/ipset
		if [ $? -ne 0 ]; then
			rc="1"
		fi
	fi

	log_action_end_msg $rc
}

flush_rules() {
	if [ ! -x $IPSET ]; then
		log_action_cont_msg " $IPSET does not exist"
	else
		log_action_begin_msg "Flushing rules"
		log_action_cont_msg " ipset"
		$IPSET destroy
	fi

	log_action_end_msg 0
}

ipset_status() {
	if [ ! -x $IPSET ]; then
		log_action_cont_msg " skipping ipset-persistent ($IPSET not exist)"
	else
		if [ ! -f /etc/iptables/ipset ]; then
			log_action_cont_msg " no rules"
		else
			log_action_cont_msg " ipset"
			cat /etc/iptables/ipset
		fi
	fi

	log_action_end_msg 0
}

case "$1" in
	start|restart|reload|force-reload)
		load_rules
		;;
	save)
		save_rules
		;;
	stop)
		echo 'Automatic flushing disabled, use "flush" instead of "stop"'
		;;
	flush)
		flush_rules
		;;
	status)
		ipset_status
		;;
	*)
		echo "Usage: $0 {start|restart|reload|force-reload|save|flush|status}" 1>&2
		exit 1
		;;
esac

exit "$rc"
