# https://github.com/h5bp/server-configs-apache

# Cross-origin
Include conf-available/h5bp/cross-origin/images.conf
Include conf-available/h5bp/cross-origin/web_fonts.conf

# Errors
Include conf-available/h5bp/errors/error_prevention.conf

# Media types and character encodings
Include conf-available/h5bp/media_types/media_types.conf
Include conf-available/h5bp/media_types/character_encodings.conf

# Rewrites
Include conf-available/h5bp/rewrites/rewrite_engine.conf

# Security
ServerTokens Prod
Include conf-available/h5bp/security/file_access.conf
Include conf-available/h5bp/security/referrer-policy.conf
Include conf-available/h5bp/security/server_software_information.conf
Include conf-available/h5bp/security/x-content-type-options.conf
# Include conf-available/h5bp/security/x-frame-options.conf

# Web performance
Include conf-available/h5bp/web_performance/compression.conf
Include conf-available/h5bp/web_performance/cache_expiration.conf
Include conf-available/h5bp/web_performance/no_etags.conf
