#!/bin/bash
#
# Download SES emails from the S3 bucket as an icron job.
#
# DEPENS        :apt-get install incron s3cmd

SYSLOG_TAG="ses-to-imap"

set -e

# File generated by endpoint.php
SNS_FILE="$1"

# Dependency
hash s3cmd

# Wait for the file operation to finish
sleep 1

# Check argument
test -r "$SNS_FILE"
RECIPIENT="$(basename "$SNS_FILE")"
# SNS_FILE's name must be an email address
if [[ ! "$RECIPIENT" =~ ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,10}$ ]]; then
    logger -t "${SYSLOG_TAG}" "SES Email address is invalid, delivering to postmaster. '${RECIPIENT}'"
    RECIPIENT="postmaster"
fi

# Temporary list file and message download directory
SNS_TEMP="$(mktemp)"
MSG_TEMP_DIR="$(mktemp -d)"
# shellcheck disable=SC2064
trap "rm -f '$SNS_TEMP'; rmdir '$MSG_TEMP_DIR'" EXIT HUP INT QUIT PIPE TERM

# Move S3 path list file to another location
flock --exclusive --wait 60 "$SNS_FILE" mv "$SNS_FILE" "$SNS_TEMP"

# Download messages from S3
< "$SNS_TEMP" xargs -r -I % s3cmd --quiet get --delete-after-fetch % "${MSG_TEMP_DIR}/"

# Deliver to local mailbox
while read -r MSG_ID; do
    /usr/sbin/sendmail "$RECIPIENT" < "$MSG_ID"
    logger -t "${SYSLOG_TAG}" "SES Message delivered: ${MSG_ID##*/} to: ${RECIPIENT}"
    rm "$MSG_ID"
done < <(find "${MSG_TEMP_DIR}/" -type f)
