#!/bin/bash

NOD_USER="EAV-1111111111"
NOD_PASS="rrrrrrrrrr"
NOD_EXPIRE="2015-04-15"

EXPIRE_WARN_DAYS=15

# http://exp01.eset.com/getlicexp
# mailto:zoltan.kiss@sicontact.hu

MIRROR="/var/www/nod-update/server"

# SETUP:
# ------

#    <Directory />
#        AllowOverride AuthConfig
#    </Directory>

# cat <<EOF > ".htaccess"
# AuthType Basic
# AuthName "Access NOD32 updates"
# AuthUserFile /var/www/torok.nod32/httpauth
# AuthGroupFile /dev/null
# Require valid-user
# EOF

# create auth file #
# htpasswd -cb "httpauth" nod32 nod32
# update user
# htpasswd -b "httpauth" user2 pass2

# wget -O favicon.ico "http://www.eset.hu/$(wget -qO- "http://www.eset.hu/" | grep -m1 icon | cut -d'"' -f2)"


#NOD32 2.7
ESET_URL2="http://um21.eset.com"
ESET_DIR2="nod_upd"

#NOD32 >= 3.0
#ESET_URL3="http://update.eset.com"
ESET_URL3="http://um21.eset.com"
ESET_DIR3="eset_upd"

#http://um21.eset.com
#http://91.228.167.21
#http://um01.eset.com
#http://91.228.166.14
#http://um03.eset.com
#http://91.228.166.16
#http://um05.eset.com
#http://91.228.167.133
#http://um07.eset.com
#http://38.90.226.37
#http://um09.eset.com
#http://38.90.226.39

#NOD32 >= 5.0
ESET_URL5="http://um21.eset.com"
ESET_DIR5="eset_upd/v5"

ESET_FILE="update.ver"
ESET_UPDATEVER_INI_DIR="/tmp"
ESET_UPDATEVER_INI="${ESET_UPDATEVER_INI_DIR}/${ESET_FILE}"
#ESET_UPDATEVER_INI_MOD="${ESET_UPDATEVER_INI_DIR}/${ESET_FILE}2_$$"
ESET_NUPS="${ESET_UPDATEVER_INI_DIR}/nod32-list$$"
ESET_NUPS_DL="${ESET_UPDATEVER_INI_DIR}/nod32-d-l$$"

DAEMON="NOD32mirror[$$]"
#WGET_DEF="-t 9 -T 9 -N -nH -r --user=\"$NOD_USER\" --password=\"$NOD_PASS\" -U \"ESS Update (Windows; U; 32bit; VDB 1870; BPC 3.0.566.0; OS: 5.2.3790 SP 2.0 NT; LNG 1033; x64c)\""
#WGET_DEF="-t 9 -T 9 -N -nH -r --user=\"$NOD_USER\" --password=\"$NOD_PASS\" -U \"ESS Update (Windows; U; 32bit; VDB 6937; BPC 4.0.474.0; OS: 5.1.2600 SP 3.0 NT; CH 0.0; LNG 1033; x32c; UPD http://93.184.71.27/eset_upd; APP eavbe; BEO 1; CPU 6092; ASP 0.10)\""
#WGET_DEF="-t 9 -T 9 -N -nH -r --auth-no-challenge --user=\"$NOD_USER\" --password=\"$NOD_PASS\" -U \"ESS Update (Windows; U; 32bit; VDB 7361; BPC 4.2.40.23; OS: 5.1.2600 SP 3.0 NT; CH 0.0; LNG 1038; x32c; UPD http://um10.eset.com/eset_upd; APP eavbe; BEO 1; CPU 1356; ASP 0.10)\""
WGET_DEF="-t 3 -T 3 -N -nH -r --auth-no-challenge --user=\"$NOD_USER\" --password=\"$NOD_PASS\" -U \"ESS Update (Windows; U; 32bit; PVT F; VDB 18166; BPC 5.0.2228.1; OS: 6.1.7601 SP 1.0 NT; TDB 18166; CL 1.1.1; LNG 1038; x32c; APP eea; BEO 1; ASP 0.10; FW 0.0; PX 0; PUA 1; CD 0; RA 0; HWF: 0100DD77-56C9-6057-724A-1A28716ED715)\""

WGET="wget -q $WGET_DEF"
WGET_NV="wget -nv $WGET_DEF"
WGET_SPIDER="wget --spider -q -t 1 -T 3"

IGNORE_LANG="ch.nup cz.nup fr.nup ge.nup hr.nup it.nup jp.nup nl.nup pl.nup pt.nup sk.nup sp.nup"
IGNORE_LANG3="bgr.nup chs.nup cht.nup csy.nup dan.nup deu.nup esn.nup fin.nup fra.nup hrv.nup ita.nup nld.nup nor.nup plk.nup ptb.nup rom.nup rus.nup sky.nup slv.nup sve.nup trk.nup ukr.nup"

# log <message level name> <messages>...
log() {
    [ -z "$LOG_MODE" ] && return 1
    [ -z "$LOG_LEVEL" ] && return 2

    MSG_LEVEL_TEXT="$1"
    shift

    case "$MSG_LEVEL_TEXT" in
        LOG_VERBOSE)
            MSG_LEVEL=1
            ;;
        LOG_INFO)
            MSG_LEVEL=3
            ;;
        LOG_ERROR)
            MSG_LEVEL=5
            ;;
        LOG_DEBUG|*)
            MSG_LEVEL=0
            ;;
    esac

    if [ "$MSG_LEVEL" -lt "$LOG_LEVEL" ]; then
        return
    fi
    case "$LOG_MODE" in
        console)
            echo "$DAEMON: ($MSG_LEVEL) $@" 1>&2
            ;;
        syslog)  # syslog: LOG_INFO level (3) and up
            [ "$MSG_LEVEL" -ge 3 ] && logger -t "$DAEMON" "$@"
            ;;
    esac
}

die() {
    log LOG_ERROR "ERROR: $@"
    #stderr
    echo "$2" >&2
    exit $1
}

inset() {
    local SET_E
    local IN_SET_ELEMENT="$1"
    [ -z "$IN_SET_ELEMENT" ] && return 1
    shift
    local IN_SET="$*"
    [ -z "$IN_SET" ] && return 2

    for SET_E in $IN_SET
    do
        [ "$SET_E" = "$IN_SET_ELEMENT" ] && return 0
    done
    return 3
}

updatever() {
    local URL="$1"
    local DIR="$2"

    log LOG_VERBOSE "starting update check"
    log LOG_DEBUG "update.ver d/l:  $WGET \"$URL/$DIR/$ESET_FILE\""
    eval "$WGET -O \"${DIR}/${ESET_FILE}\" \"$URL/$DIR/$ESET_FILE\"" &> /dev/null || die 1 "update file d/l failure"

    log LOG_DEBUG "checking rar"
    if file -b "${DIR}/${ESET_FILE}" 2> /dev/null | grep -q "^RAR archive data"; then
        log LOG_DEBUG "extracting update.ver"
        unrar x -o+ "${DIR}/${ESET_FILE}" "$ESET_UPDATEVER_INI_DIR" &> /dev/null || die 9 "unpacking failure"
        #rm -f "$ESET_FILE" 2> /dev/null || die 8

        log LOG_DEBUG "checking servers"
        grep "^Other=" "$ESET_UPDATEVER_INI" 2> /dev/null | tr -d '\r' | \
         sed 's/, /\n/g' | grep -o "http://.*" | while read SERVER
        do
            log LOG_DEBUG "HTTP/HEAD: ${SERVER}"
            eval "$WGET_SPIDER \"${SERVER}/update.ver\"" || \
             log LOG_INFO "server failure: $SERVER - ret:$?"
        done

        log LOG_DEBUG "getting .nup-s' names"
        grep "^file=/" "$ESET_UPDATEVER_INI" 2> /dev/null | tr -d '\r' | \
         cut -c 6- | while read NUP
        do
            inset "${NUP:(-6)}" "$IGNORE_LANG" || \
             inset "${NUP:(-7)}" "$IGNORE_LANG3" || \
             # FIXME
             grep -q "/mod_021_horus/\|/mod_010_smon/" <<< "${NUP}" || \
              echo "${URL}${NUP}" >> "$ESET_NUPS"
        done 2> /dev/null || die 3 "update file process error"

        # `sed` to local directory
#        sed 's/^file=\(.*\)$/file=\/nod32\1/;s/^Other=.*$/Other=20@http:\/\/domain.hu\/nod32\/, 20@http:\/\/domain.hu:80\/nod32\//' \
#            < "$ESET_UPDATEVER_INI" > "$ESET_UPDATEVER_INI_MOD" || die 6
#        log LOG_VERBOSE "`(echo -n "[HOSTS] "; grep "^Other=" "$ESET_UPDATEVER_INI_MOD")`"

        # repack
#        mv -f "$ESET_UPDATEVER_INI_MOD" "$ESET_UPDATEVER_INI" || die 10
#        rar a -ep "$ESET_FILE" "$ESET_UPDATEVER_INI" &> /dev/null || die 7
    else
        log LOG_DEBUG "not a RAR file: ${DIR}/${ESET_FILE}"
        die 2 "not RAR file"
    fi
    log LOG_VERBOSE "checked $URL/$DIR"
}


# --------------------------------------------------------------------------------------------------


if tty --quiet; then
    LOG_MODE=console
else
    LOG_MODE=syslog
fi

# FIXME optargs
case "$1" in
    --debug)
        LOG_LEVEL=0  # LOG_DEBUG
        ;;
    -v|--verbose)
        LOG_LEVEL=1  # LOG_VERBOSE
        ;;
    *)
        LOG_LEVEL=3  # LOG_INFO
        ;;
esac
log LOG_DEBUG "LOG_MODE=$LOG_MODE, LOG_LEVEL=$LOG_LEVEL"

log LOG_INFO "update starting..."

log LOG_DEBUG "required commands"
which wget file unrar rar logger mailx &> /dev/null || die 99 "required command not found"

log LOG_DEBUG "checking expire"
NOW_SEC="`date "+%s"`"
EXPIRE_SEC="`date --date "$NOD_EXPIRE" "+%s"`"
EXPIRE_DAYS=$(( (EXPIRE_SEC - NOW_SEC) / 86400 ))
log LOG_DEBUG "expires on $NOD_EXPIRE"
if [ $EXPIRE_DAYS -lt $EXPIRE_WARN_DAYS ]; then
    log LOG_INFO "+ATTENTION+ licence is about to expire on $NOD_EXPIRE"

    cat <<EOF | LANG=hu_HU mailx -S from="NOD32 Tükör <root@`hostname`>" -s "ESET NOD32 Antivírus licenc lejár" root
Kedves root!

A $NOD_USER licenc lejár ekkor: $NOD_EXPIRE

Kérlek hosszabbítsd meg! https://www.eset.hu/vasarlas/hosszabbitas

Üdvözöllek
$DAEMON
EOF
fi

pushd "$MIRROR" &> /dev/null

echo -n > "$ESET_NUPS"


#log LOG_DEBUG "getting and parsing update.ver v2.7"
#updatever "$ESET_URL2" "$ESET_DIR2"
#cp -f "$ESET_DIR2/$ESET_FILE" "$ESET_FILE" &> /dev/null

log LOG_DEBUG "getting and parsing update.ver >= v3.0"
updatever "$ESET_URL3" "$ESET_DIR3"

log LOG_DEBUG "getting and parsing update.ver >= v5.0"
updatever "$ESET_URL5" "$ESET_DIR5"


log LOG_DEBUG ".nup-s to check: `cat "$ESET_NUPS"`"

log LOG_DEBUG "downloading .nup-s"
[ -s "$ESET_NUPS" ] || die 4 "no .nup-s"
log LOG_VERBOSE "`wc -l < "$ESET_NUPS"` .nup-s to check"

log LOG_DEBUG ".nup download log: $ESET_NUPS_DL"

eval "$WGET_NV -i \"${ESET_NUPS}\"" > "$ESET_NUPS_DL" 2>&1 || die 5 ".nup-s d/l failed"
DIFFS="`grep -c " -> " < "$ESET_NUPS_DL"`"

# v2
#http://download.eset.com/download/win/v2st/ndntenst.exe
#http://download.eset.com/download/win/v2ad/ndntenad.exe
#http://download.eset.com/download/win/v2st/ndnthust.exe
#http://download.eset.com/download/win/v2ad/ndnthuad.exe
eval "$WGET -i-" &> /dev/null <<EOF || die 10 "program d/l error"
http://download.eset.com/download/win/eavbe/eavbe_nt32_enu.msi
http://download.eset.com/download/win/eavbe/eavbe_nt64_enu.msi
http://download.eset.com/download/win/eavbe/eavbe_nt32_hun.msi
http://download.eset.com/download/win/eavbe/eavbe_nt64_hun.msi
http://download.eset.com/download/win/eav/eav_nt32_enu.msi
http://download.eset.com/download/win/eav/eav_nt64_enu.msi
http://download.eset.com/download/win/eav/eav_nt32_hun.msi
http://download.eset.com/download/win/eav/eav_nt64_hun.msi
http://download.eset.com/download/win/eea/eea_nt32_enu.msi
http://download.eset.com/download/win/eea/eea_nt64_enu.msi
http://download.eset.com/download/win/eea/eea_nt32_hun.msi
http://download.eset.com/download/win/eea/eea_nt64_hun.msi
http://download.eset.com/download/ra/era_console_nt32_enu.msi
http://download.eset.com/download/ra/era_server_nt32_enu.msi
EOF

log LOG_INFO "$DIFFS updated of $(wc -l < "$ESET_NUPS") files (expires in $EXPIRE_DAYS days)"

log LOG_DEBUG "cleaning up update.ver, .nup-list"
rm -f "$ESET_UPDATEVER_INI" "$ESET_NUPS" "$ESET_NUPS_DL" &> /dev/null

popd &> /dev/null

exit 0
