#!/bin/bash
### BEGIN INIT INFO
# Provides:          halt-alert
# Required-Start:
# Required-Stop:     $remote_fs courier-mta
# Default-Start:
# Default-Stop:      0 1 6
# Short-Description: Alert on system shutdown
### END INIT INFO

# VERSION       :0.2.1
# DATE          :2016-08-22
# REFS          :http://refspecs.linuxfoundation.org/LSB_4.1.0/LSB-Core-generic/LSB-Core-generic/tocsysinit.html
# DOCS          :https://wiki.debian.org/LSBInitScripts
# AUTHOR        :Viktor Szépe <viktor@szepe.net>
# URL           :https://github.com/szepeviktor/debian-server-tools
# LICENSE       :The MIT License (MIT)
# LOCATION      :/etc/init.d/halt-alert

NAME="halt-alert"
ADDRESS="sms@szepe.net"

# Read configuration variable file if it is present
[ -r /etc/default/${NAME} ] && . /etc/default/${NAME}

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
. /lib/lsb/init-functions

do_stop() {
  # Return
  #   0 if daemon has been stopped
  #   1 if daemon was already stopped
  #   2 if daemon could not be stopped
  #   other if a failure occurred
  if echo -e "Host HALTED at $(date -R)\n\n$(COLUMNS=120 w --ip-addr)" \
    | mail -s "Host $(hostname -f) is HALTED" ${ADDRESS}; then
    # Wait for message delivery
    sleep 5
    return 0
  else
    return 3
  fi
}

case "$1" in

  start|status)
    # No-op
    ;;

  stop)
    [ "$VERBOSE" != no ] && log_daemon_msg "Sending alert" "$NAME"
    do_stop
    case "$?" in
      0|1)
        [ "$VERBOSE" != no ] && log_end_msg 0
        ;;
      2)
        [ "$VERBOSE" != no ] && log_end_msg 1
        ;;
    esac
    ;;

  restart|reload|force-reload)
    echo "Error: argument '$1' not supported" 1>&2
    exit 3
    ;;

  *)
    echo "Usage: ${SCRIPTNAME} start|stop" 1>&2
    exit 3
    ;;

esac

exit 0
