#!/bin/bash
#
# Run ntpdate daily to correct the system clock.
#
# VERSION       :0.2
# DATE          :2014-10-22
# AUTHOR        :Viktor Szépe <viktor@szepe.net>
# LICENSE       :The MIT License (MIT)
# URL           :https://github.com/szepeviktor/debian-server-tools
# BASH-VERSION  :4.2+
# DEPENDS       :apt-get install iproute heirloom-mailx
# LOCATION      :/usr/local/sbin/ntpdated
# CRON-HOURLY   :/usr/local/sbin/ntpdated

# Options in /etc/default/ntpdate

/usr/sbin/ntpdate-debian -s

#TODO: cron.d @reboot, @hourly
