#!/bin/bash
#
# Run ntpdate daily and on reboot to correct the system clock.
#
# VERSION       :0.3
# DATE          :2014-12-26
# AUTHOR        :Viktor Szépe <viktor@szepe.net>
# LICENSE       :The MIT License (MIT)
# URL           :https://github.com/szepeviktor/debian-server-tools
# BASH-VERSION  :4.2+
# LOCATION      :/usr/local/sbin/ntpdated
# CRON.D        :@reboot  root  /usr/local/sbin/ntpdated
# CRON.D        :@hourly  root  /usr/local/sbin/ntpdated

# Options in /etc/default/ntpdate

/usr/sbin/ntpdate-debian -s
