    # mod_remoteip - Amazon CloudFront is trusted by us
    RemoteIPHeader X-Forwarded-For
    RemoteIPTrustedProxyList conf-available/amazon-cloudfront-ip.list

    # Allow file access and .htaccess usage
    <Directory "/home/${SITE_USER}/website">
        Options FollowSymLinks
        AllowOverride All
        # Check Amazon CloudFront IP list
        Require expr "%{REMOTE_ADDR} != %{CONN_REMOTE_ADDR}"
        Require local
    </Directory>

    # Allow traffic only from Amazon CloudFront
    RewriteCond "%{HTTP:X-Amz-Cf-Id}" ="" [OR]
    RewriteCond "%{HTTP:Via}" =""
    RewriteRule "^" - [F]
