    # mod_remoteip - Cloudflare is trusted by us
    RemoteIPHeader CF-Connecting-IP
    RemoteIPTrustedProxyList conf-available/cloudflare-ipv4.list

    # Allow file access and .htaccess usage
    <Directory "/home/${SITE_USER}/website">
        Options FollowSymLinks
        AllowOverride All
        # Check Cloudflare IP list
        Require expr "%{REMOTE_ADDR} != %{CONN_REMOTE_ADDR}"
        Require local
    </Directory>

    # Cloudflare Warp may send non-CDN traffic
    RewriteCond "%{HTTP:CF-Connecting-IP}" ="" [OR]
    RewriteCond "%{HTTP:CF-Ray}" ="" [OR]
    RewriteCond "%{HTTP:X-Forwarded-For}" =""
    RewriteRule "^" - [F]
