# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "Docs"

on:  # yamllint disable-line rule:truthy
    push:
        branches:
        - "master"
        paths:
        - "**/*.md"
    pull_request:
        paths:
        - "**/*.md"
# Add [skip ci] to commit message to skip CI.

permissions:
    contents: "read"

concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    markdown:
        name: "Markdown"
        runs-on: "ubuntu-20.04"
        steps:
        -
            name: "Checkout repository"
            uses: "actions/checkout@v3"
        -
            name: "Check Markdown documents"
            uses: "DavidAnson/markdownlint-cli2-action@v9"
            with:
                globs: "**/*.md"
