#!/bin/bash
#
# Ping healthchecks.io.
#
# VERSION       :0.1.0
# LOCATION      :/usr/local/bin/healthchecks-test.sh

set -e

HEALTHCHECKS_URL="$1"

test -n "$HEALTHCHECKS_URL"

wget --quiet --tries=3 --output-document=- "$HEALTHCHECKS_URL" | grep -Fx "OK"
