#!/bin/bash
#
# Connect to gamin server for session test.
#
# VERSION       :1.2.2
# DOCS          :https://people.gnome.org/~veillard/gamin/debug.html
# SOURCE        :gamin/tests/.lib/testgam
# DEPENDS       :/usr/local/bin/testgam
# DEPENDS       :apt-get install gamin
# LOCATION      :/usr/local/sbin/gamin-test.sh

TESTGAM="/usr/local/bin/testgam"
IMAP_USER="virtual"

set -e

[ -x "$TESTGAM" ]

Sudo_virtual() {
    local GAMTMP="$(sudo -u "$IMAP_USER" -- mktemp)"
    # shellcheck disable=SC2064
    trap "sudo -u '$IMAP_USER' -- rm -f '$GAMTMP'" EXIT HUP QUIT PIPE TERM

    echo -e "connect test\npending\nsleep 1\ndisconnect" > "$GAMTMP"
    sudo -u "$IMAP_USER" -- "$TESTGAM" "$GAMTMP" \
        | grep -Fx "pending 0"
}

# Expected output:
#     connected to test
#     pending 0
#     disconnected
# Exit status of grep is 1 if not found
"$TESTGAM" <(echo -e "connect test\npending\nsleep 1\ndisconnect") \
    | grep -Fx "pending 0"
