#!/bin/bash
#
# Connect to gamin server for session test.
#
# VERSION       :1.2.4
# DOCS          :https://people.gnome.org/~veillard/gamin/debug.html
# SOURCE        :gamin/tests/.lib/testgam
# DEPENDS       :/usr/local/bin/testgam
# DEPENDS       :apt-get install gamin
# LOCATION      :/usr/local/sbin/gamin-test.sh

TESTGAM="/usr/local/bin/testgam"
IMAP_USER="virtual"

set -e

test -x "$TESTGAM"

Gamin_test_virtual()
{
    local GAMTMP

    GAMTMP="$(sudo -u "$IMAP_USER" -- mktemp)"
    # shellcheck disable=SC2064
    trap "sudo -u '$IMAP_USER' -- rm -f '$GAMTMP'" EXIT HUP QUIT PIPE TERM

    printf 'connect test\npending\nsleep 1\ndisconnect\n' >"$GAMTMP"
    sudo -u "$IMAP_USER" -- "$TESTGAM" "$GAMTMP" \
        | grep -F -x 'pending 0'
}

# Expected output:
#     connected to test
#     pending 0
#     disconnected
# Exit status of grep is 1 if not found
"$TESTGAM" <(printf 'connect test\npending\nsleep 1\ndisconnect\n') \
    | grep -F -x 'pending 0'
