#!/bin/bash
#
# Ping Redis cache.
#
# VERSION       :0.1.0
# DEPENDS       :apt-get install netcat-openbsd
# LOCATION      :/usr/local/sbin/redis-server-test.sh

set -e

echo "ping" | nc -C -q 10 localhost 6379 | grep -F "+PONG"
