#!/bin/bash
#
# Check the randomness of /dev/random.
#
# VERSION       :0.2.0
# LOCATION      :/usr/local/sbin/rng-tools-test.sh

set -e

/usr/bin/rngtest --blockstats=10 --blockcount=10 </dev/random 2>&1 \
    | grep -F -x 'rngtest: FIPS 140-2 successes: 10'
