#!/bin/bash
#
# Execute 7zip with high PPMd compression
#
# VERSION       :0.1.0
# DEPENDS       :apt-get install p7zip-full
# LOCATION      :/usr/local/bin/7z-ppmd

7z a -mx9 -m0=PPMd:mem=256m -m1=LZMA2 "$@"
