#!/bin/bash
#
# Retrieve PTR records for a /24 (Class C) subnetwork.
#
# VERSION       :1.2.0
# DATE          :2018-05-06
# AUTHOR        :Viktor Szépe <viktor@szepe.net>
# URL           :https://github.com/szepeviktor/debian-server-tools
# LICENSE       :The MIT License (MIT)
# BASH-VERSION  :4.2+
# DEPENDS       :apt-get install dnsutils bind9-host
# LOCATION      :/usr/local/bin/cnet

OCTETS="$1"
NS="$2"

if [ -z "$OCTETS" ]; then
    echo "Usage: ${BASH_SOURCE[0]} IPv4" 1>&2
    exit 1
fi

for LAST_OCTET in {0..255}; do
    CURRENT_IP="${OCTETS%.*}.${LAST_OCTET}"

    if hash dig 2>/dev/null; then
        if [ -n "$NS" ]; then
            # global-queryopt first
            ANSWER="$(dig +noall +answer "@${NS}" -x "$CURRENT_IP")"
        else
            # global-queryopt first
            ANSWER="$(dig +noall +answer -x "$CURRENT_IP")"
        fi
        echo "${ANSWER:-PTR record is not available for ${CURRENT_IP}}"
    else
        # shellcheck disable=SC2086
        host -t PTR "$CURRENT_IP" ${NS}
    fi

    if [ "$CURRENT_IP" == "$OCTETS" ]; then
        # https://wiki-dev.bash-hackers.org/commands/builtin/printf#modifiers
        printf '=%.0s' {1..70}
        printf '\n\n'
    fi
done
