#!/bin/bash
#
# Retrieve PTR records for a /24 (Class C) subnetwork.
#
# VERSION       :1.1.0
# DATE          :2018-05-06
# AUTHOR        :Viktor Szépe <viktor@szepe.net>
# URL           :https://github.com/szepeviktor/debian-server-tools
# LICENSE       :The MIT License (MIT)
# BASH-VERSION  :4.2+
# DEPENDS       :apt-get install bind9-host
# LOCATION      :/usr/local/bin/cnet

OCTETS="$1"

if [ -z "$OCTETS" ]; then
    echo "Usage: $0 1.2.3.4" 1>&2
    exit 1
fi

for LAST_OCTET in {0..255}; do
    CURRENT_IP="${OCTETS%.*}.${LAST_OCTET}"

    host -t PTR "$CURRENT_IP"

    if [ "$CURRENT_IP" == "$OCTETS" ]; then
        printf '**********************************************************************\n\n'
    fi
done
