#!/bin/bash
#
# Retrieve PTR record for a /24 (Class C) subnetwork.
#
# VERSION       :1.0.0
# DATE          :2015-07-01
# AUTHOR        :Viktor Szépe <viktor@szepe.net>
# URL           :https://github.com/szepeviktor/debian-server-tools
# LICENSE       :The MIT License (MIT)
# BASH-VERSION  :4.2+
# DEPENDS       :apt-get install bind9-host
# LOCATION      :/usr/local/bin/cnet

OCTETS="$1"

[ -z "$OCTETS" ] && echo "Usage: $0 1.2.3.4" >&2

for LAST_OCTET in $(seq 0 255); do
    CURRENT_IP="${OCTETS%.*}.${LAST_OCTET}"

    host -t PTR "$CURRENT_IP"
    if [ "$CURRENT_IP" == "$OCTETS" ]; then
        echo "***************************"
        echo
    fi
done
