#!/bin/bash
#
# Show disk usage in kB by file extension.
#
# VERSION       :0.3.0
# LOCATION      :/usr/local/bin/du-ext

find . -type f -printf '%f\n' | grep -o '\.[^.]\+$' | sort -u \
    | {
        while read -r FILE; do
            printf '%s ' "$FILE"
            find . -type f -name "*${FILE}" -print0 \
                | du --files0-from=- -k --total | tail -n 1 | cut -f 1
        done

        # Extensionless files
        printf 'N/A '
        find . -type f -not -name "*.*" -print0 \
            | du --files0-from=- -k --total | tail -n 1 | cut -f 1 | grep -v -F -x 'N/A 0'
    } | sort -n -k 2
