#!/bin/bash
#
# Display country of given IP address.
#
# VERSION       :0.1.1
# DATE          :2019-04-05
# URL           :https://github.com/szepeviktor/debian-server-tools
# AUTHOR        :Viktor Szépe <viktor@szepe.net>
# LICENSE       :The MIT License (MIT)
# BASH-VERSION  :4.2+
# DEPENDS       :apt-get install mmdb-bin
# LOCATION      :/usr/local/bin/geoiplookup-ctry

test -n "$1" || exit 10

mmdblookup --file /var/lib/GeoIP/GeoLite2-Country.mmdb --ip "$1" registered_country iso_code \
    | sed -n -e '0,/^\s\+"\([A-Z]\+\)" <\S\+>$/s//\1/p'
