#!/bin/bash

test -n "$1" || exit 10

mmdblookup --file /var/lib/GeoIP/GeoLite2-ASN.mmdb --ip "$1" \
    | sed -n -e 's/^\s\+\(\([0-9]\+\)\|"\(.\+\)"\) <\S\+>$/\2\3/;TNext;x;/./{x;H;bNext};x;h;:Next;${x;s/\n/ /g;s/^/AS/;p}'
