#!/bin/bash
#
# Display AS of given IP address.
#
# VERSION       :0.1.0
# DATE          :2019-04-05
# URL           :https://github.com/szepeviktor/debian-server-tools
# AUTHOR        :Viktor Szépe <viktor@szepe.net>
# LICENSE       :The MIT License (MIT)
# BASH-VERSION  :4.2+
# DEPENDS       :apt-get install mmdb-bin
# LOCATION      :/usr/local/bin/geoiplookup-as

test -n "$1" || exit 10

mmdblookup --file /var/lib/GeoIP/GeoLite2-ASN.mmdb --ip "$1" \
    | sed -n -e 's/^\s\+\(\([0-9]\+\)\|"\(.\+\)"\) <\S\+>$/\2\3/;TNext;x;/./{x;H;bNext};x;h;:Next;${x;s/\n/ /g;s/^/AS/;p}'
