#!/bin/bash
#
# Display GitHub download URL of a file.
#
# VERSION       :0.1.0
# DATE          :2016-07-27
# AUTHOR        :Viktor Szépe <viktor@szepe.net>
# URL           :https://github.com/szepeviktor/debian-server-tools
# LICENSE       :The MIT License (MIT)
# BASH-VERSION  :4.2+
# DEPENDS       :apt-get install git jq
# LOCATION      :/usr/local/bin/ghurl

# $1 is empty or does not exist
# test for a git repo
ORIGIN_URL="$(git config --get remote.origin.url)"
# empty URL?

USER_REPO="${ORIGIN_URL#*:}"
USER_REPO="${USER_REPO%.git}"
# should look like "[.A-Za-z0-9_-]\+\.[.A-Za-z0-9_-]\+"

wget -qO- "https://api.github.com/repos/${USER_REPO}/contents/${1}" \
    | jq -r ".download_url"
# check URL
