#!/bin/bash
#
# Extract hostname from URL and execute BIND9 host command.
#
# VERSION       :0.1.2
# DATE          :2014-11-19
# AUTHOR        :Viktor Szépe <viktor@szepe.net>
# LICENSE       :The MIT License (MIT)
# URL           :https://github.com/szepeviktor/debian-server-tools
# BASH-VERSION  :4.2+
# DEPENDS       :apt-get install bind9-host
# LOCATION      :/usr/local/bin/host

# Only works with URL as the last option.

Un_url() {
    localARG="$1"

    # Strip protocol, e.g. http://
    ARG="${ARG#*//}"
    # Strip path and query, e.g. /contact/
    ARG="${ARG%%/*}"
    # Strip port, e.g. :8080
    echo "${ARG%:*}"
}

which host &> /dev/null || exit 1
[ -z "$1" ] && exit 2

declare -a ARG_ARR
declare -i LAST_INDEX

# Copy command line arguments into ARG_ARR
for ARG; do
    ARG_ARR+=("${ARG}")
done

LAST_INDEX="$(( ${#ARG_ARR[@]} - 1 ))"
# Extract hostname
ARG_ARR[$LAST_INDEX]="$(Un_url "${ARG_ARR[$LAST_INDEX]}")"

# Empty hostname
[ -z "${ARG_ARR[$LAST_INDEX]}" ] && exit 3

/usr/bin/host "${ARG_ARR[@]}"
