#!/bin/bash
#
# Extract hostname from URL and execute BIND9 host command.
#
# VERSION       :0.3.0
# DATE          :2016-03-06
# AUTHOR        :Viktor Szépe <viktor@szepe.net>
# LICENSE       :The MIT License (MIT)
# URL           :https://github.com/szepeviktor/debian-server-tools
# BASH-VERSION  :4.2+
# DEPENDS       :apt-get install bind9-host
# LOCATION      :/usr/local/bin/host

# Usage
#
# The URL must be the last option.

Get_hostname() {
    local URL="$1"

    # Strip protocol, e.g. http://
    URL="${URL#*//}"
    # Strip path and query, e.g. /contact/
    URL="${URL%%/*}"
    # Strip port, e.g. :8080
    if [ "${URL//[^:]/}" == ":" ]; then
        echo "${URL%:*}"
        return
    fi

    echo "$URL"
}

[ -x /usr/bin/host ] || exit 1
[ -z "$*" ] && exit 2

declare -a ARG_ARR
declare -i LAST_INDEX

# Copy command line arguments into ARG_ARR
for ARG; do
    ARG_ARR+=( "${ARG}" )
done

LAST_INDEX="$(( ${#ARG_ARR[@]} - 1 ))"

# Extract hostname
ARG_ARR[$LAST_INDEX]="$(Get_hostname "${ARG_ARR[$LAST_INDEX]}")"

# Empty hostname
[ -z "${ARG_ARR[$LAST_INDEX]}" ] && exit 3

exec /usr/bin/host "${ARG_ARR[@]}"
