#!/bin/bash
#
# Display DNS record and whois record of an IP address.
#
# VERSION       :0.1.1
# DATE          :2016-06-08
# AUTHOR        :Viktor Szépe <viktor@szepe.net>
# LICENSE       :The MIT License (MIT)
# URL           :https://github.com/szepeviktor/debian-server-tools
# BASH-VERSION  :4.2+
# DEPENDS       :apt-get install bind9-host
# LOCATION      :/usr/local/bin/hostinfo

HOST="$1"
test -z "$HOST" && exit 1

host "$HOST"
whoistop "$HOST"
