#!/bin/bash
#
# Safe reboot.
#
# VERSION       :0.4.0
# DATE          :2017-02-10
# AUTHOR        :Viktor Szépe <viktor@szepe.net>
# URL           :https://github.com/szepeviktor/debian-server-tools
# LICENSE       :The MIT License (MIT)
# BASH-VERSION  :4.2+
# DEPENDS       :apt-get install grub-pc psmisc
# LOCATION      :/usr/local/sbin/reboot

# Usage
#
#     REBOOT=1 reboot

GRUB_CONFIG="/boot/grub/grub.cfg"

if [ "$REBOOT" != 1 ]; then
    echo "Try  REBOOT=1 reboot $*"
    exit 100
fi

if [ -f "/extlinux.conf" ] && [ -f "/ldlinux.sys" ]; then
    # shellcheck disable=SC2016
    FIRST_ROOT="$(sed -n -e '0,/^append /s/^.*\sroot=\(\S\+\).*$/\1/p' /extlinux.conf)"
else
    # shellcheck disable=SC2016
    FIRST_ROOT="$(sed -n -e '/^menuentry/,${s/^\s*linux\b.*root=\(\S\+\).*$/\1/p;/^}/q}' "$GRUB_CONFIG")"
fi

DISK=""

# Find block device by name
if [ "${FIRST_ROOT:0:5}" == "/dev/" ]; then
    DISK="$(realpath "$FIRST_ROOT")"
fi

# Find disk by UUID
if [ "${FIRST_ROOT:0:5}" == "UUID=" ]; then
    DISK="$(readlink -e "/dev/disk/by-uuid/${FIRST_ROOT#UUID=}")"
fi

# Disk and mounted device differ
if [ "${FIRST_ROOT:0:12}" == "/dev/mapper/" ]; then
    MOUNTED="$FIRST_ROOT"
else
    MOUNTED="$DISK"
fi

# Not a mounted block device
if [ ! -b "$DISK" ] || ! grep -q "^${MOUNTED}\s" /proc/mounts; then
    echo "Root device not found (${FIRST_ROOT})" 1>&2
    exit 1
fi

# Stop monit
clear
if [ "$(dpkg-query --showformat='${Status}' --show monit 2> /dev/null)" == "install ok installed" ]; then
    if service monit status | grep -q -F 'monit is running'; then
        service monit stop
    fi
fi

# Start the reboot process
/sbin/reboot "$@" &

# Follow syslog for 5 seconds
timeout 5 tail -f /var/log/syslog

# Watch processes exit
while :; do
    clear
    date
    pstree
    sleep 0.5
done
