#!/bin/bash
#
# Sort syslog-style lines.
#
# VERSION       :0.1.1
# DATE          :2016-05-21
# AUTHOR        :Viktor Szépe <viktor@szepe.net>
# LICENSE       :The MIT License (MIT)
# URL           :https://github.com/szepeviktor/debian-server-tools
# BASH-VERSION  :4.2+
# LOCATION      :/usr/local/bin/sortsyslog

exec sort -k 1M -k 2n -k 3
