#!/bin/bash
#
# Display only the first block of whois record.
#
# VERSION       :0.1.0
# DATE          :2015-12-07
# AUTHOR        :Viktor Szépe <viktor@szepe.net>
# LICENSE       :The MIT License (MIT)
# URL           :https://github.com/szepeviktor/debian-server-tools
# BASH-VERSION  :4.2+
# LOCATION      :/usr/local/bin/whoistop

whois "$@" | sed '/^[a-z]\+:/,/^$/!d; /^$/,$d'

# Alternative solution
#     sed '/range/ {command}'
