#!/bin/bash
#
# Display only the first block of whois record.
#
# VERSION       :0.1.2
# DATE          :2015-12-07
# AUTHOR        :Viktor Szépe <viktor@szepe.net>
# LICENSE       :The MIT License (MIT)
# URL           :https://github.com/szepeviktor/debian-server-tools
# BASH-VERSION  :4.2+
# LOCATION      :/usr/local/bin/whoistop

whois "$@" | sed -e '/^[A-Za-z]\+:/,/^$/!d; /^$/,$d'

# Alternate solution
#     sed '/range/ {command}'

# Web-based whois query
#wget -qO- "http://lg.net.telekom.hu/whois?q=$1" \
#    | sed -n -e 's|^\s*"output": "\(.*\)",\s*$|\1|; s|<br>|\n|gp' \
#    | sed -e '/^[A-Za-z]\+:/,/^$/!d; /^$/,$d'
