#!/bin/bash
#
# Display parts of the whois record of the given host's IP address.
#
# VERSION       :0.1.1
# DATE          :2015-07-18
# AUTHOR        :Viktor Szépe <viktor@szepe.net>
# LICENSE       :The MIT License (MIT)
# URL           :https://github.com/szepeviktor/debian-server-tools
# BASH-VERSION  :4.2+
# LOCATION      :/usr/local/bin/whoishost


WHOST="$1"
WINFO_REGEXP="^country:|^state:|^netname:|^origin|\(NET-"

WHOST_IP="$(host -t A "$WHOST" | head -n 1)"
WHOST_IP="${WHOST_IP##* has address }"

# Check IP
# @TODO Octets could be greater than 255
[[ "$WHOST_IP" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] \
    && whois "$WHOST_IP" | grep -Ei "$WINFO_REGEXP"
