#!/bin/bash

set -e -x

# Hardware
lspci > /root/pci.log

# Disk configuration
cat /proc/mdstat > /root/md.log
cat /proc/partitions > /root/partitions.log
pvdisplay && vgdisplay && lvdisplay > /root/lvm.log
# Defaults
ls -1 /etc/default/* > /root/etc-defaults-files.log
head -n 1000 /etc/default/* | grep -vE '^\s*#|^\s*$' | grep --color -A1000 "^==> " > /root/etc-defaults.log

# Mount /tmp in RAM above 4 GB
TOTAL_MEM="$(grep "MemTotal" /proc/meminfo | sed -e 's;.*[[:space:]]\([0-9]\+\)[[:space:]]kB.*;\1;')"
[ "$TOTAL_MEM" -gt $((4097 * 1024)) ] && sed -i 's/^#RAMTMP=no$/RAMTMP=yes/' /etc/default/tmpfs

# Mount points
# <file system> <mount point>             <type>          <options>                               <dump> <pass>
cat /etc/fstab > /root/fstab.log
cat /proc/mounts > /root/mounts.log

[ -z "$(cat /proc/swaps)" ] && debian-setup/_swap

swapoff -a
swapon -a
cat /proc/swaps > /root/swap.log

# relAtime option for filesystems
grep "\S\+\s\+/\s.*relatime" /proc/mounts || echo "WARNING: no relAtime for rootfs"

# Kernel
uname -a
# List available kernel versions
apt-cache policy "linux-image-[3456789].*"
#apt-get install linux-image-amd64=KERNEL-VERSION
# More than 1 kernel?
#aptitude --disable-columns -F"%p" search '?and(?installed, ?name(^linux-image-))'|grep -vFx "linux-image-$(dpkg --print-architecture)"
ls -l /lib/modules/
if [ -f /proc/modules ]; then
    lsmod > /root/kernel-modules.log
else
    echo "WARNING: monolithic kernel"
fi

# intel_rapl module
echo "blacklist intel_rapl" > /etc/modprobe.d/intel_rapl-blacklist.conf

# Boot
ls -latr /boot/ > /root/boot-files.log
# Verbose boot -> initscripts
sed -i 's/^#*VERBOSE=no$/VERBOSE=yes/' /etc/default/rcS
# GRUB
dpkg -l | grep "grub"
# OVH Kernel "made-in-ovh"
#     ${D}/security/ovh-kernel-update.sh
# Linode Kernels: auto renew on reboot
#     https://www.linode.com/kernels/
editor /etc/modules
ls /etc/sysctl.d/ | grep -vF "README.sysctl"
editor /etc/sysctl.conf

# Inittab on SysVinit
# Comment out getty[2-6], NOT /etc/init.d/rc
# Consider /sbin/agetty
#     1:2345:respawn:/sbin/agetty 38400 tty1
editor /etc/inittab

# Miscellaneous configuration
editor /etc/rc.local
editor /etc/profile
ls -l /etc/profile.d/
# See /input/motd-install.sh

# Networking
editor /etc/network/interfaces
#     source /etc/network/interfaces.d/*
#
#     allow-hotplug eth0
#     auto eth0
#     iface eth0 inet static
#         address INET-IP/INET-NETMASK
#         gateway GATEWAY
#         #netmask INET-NETMASK
#         #dns-nameservers INET-NS1
#     iface eth0 inet6 auto
#         dns-nameservers INET6-NS1
#     #iface eth0 inet6 static
#     #    address INET6-IP/INET6-NETMASK
#     #    gateway INET6-GW
ifconfig -a
route -n -4
route -n -6
netstat -antup

editor /etc/resolv.conf
#     # Google Public DNS
#     nameserver 8.8.8.8
#     nameserver LOCAL-NS
#     nameserver LOCAL-NS2
#     nameserver 8.8.4.4
#     #nameserver 2001:4860:4860:0:0:0:0:8888
#     #nameserver 2001:4860:4860:0:0:0:0:8844
#     options timeout:2
#     #options rotate

#     # DNS Advantage by Neustar
#     nameserver 156.154.71.1
#     nameserver LOCAL-NS
#     nameserver LOCAL-NS2
#     nameserver 156.154.70.1
#     options timeout:2
#     #options rotate

# Aruba resolvers
#     DC1-IT 62.149.128.4 62.149.132.4
#     DC3-CZ 81.2.192.131 81.2.193.227
#
# Vultr resolvers
#     Frankfurt 108.61.10.10
#
# EZIT resolvers
#     BIX 87.229.108.201 80.249.168.18
#
# OVH resolvers
#     France 213.186.33.99
#
# ATW resolvers
#     BIX 88.151.96.15 88.151.96.16 2a01:270::15 2a01:270::16

ping6 -c 4 ipv6.google.com
host -v -t A example.com|grep "^example\.com\.\s*[0-9]\+\s*IN\s*A\s*93\.184\.216\.34$"||echo "DNS error"
# View network Graph v4/v6
#     http://bgp.he.net/ip/${IP}

# SSL certificates
rm -f /etc/ssl/certs/ssl-cert-snakeoil.pem /etc/ssl/private/ssl-cert-snakeoil.key
# Update ca-certificates
wget -q -O- http://metadata.ftp-master.debian.org/changelogs/main/c/ca-certificates/unstable_changelog | pager
Getpkg ca-certificates

# Monitor certificates
( cd ${D}; ./install.sh monitoring/cert-expiry.sh )

# Show modified debconf values
debconf-show --listowners | xargs -n 1 debconf-show | grep "^\*" > /root/debconf-modified.log
# Find broken symlinks
find / -type l -xtype l -not -path "/proc/*"
debsums --all --changed | tee debsums-changed.log
# Check the presence of MD5 hashes of installed packages
for L in /var/lib/dpkg/info/*.list;do P=$(basename "$L" .list);[ -r "/var/lib/dpkg/info/${P}.md5sums" ]||echo "$P";done
# Sanitize files
rm -vrf /var/lib/clamav /var/log/clamav

# Customized files
HOSTING_COMPANY="$(Data get-value system.hosting-company)"
find / -iname "*${HOSTING_COMPANY}*"
grep -ir "${HOSTING_COMPANY}" /etc/
dpkg -l | grep -i "${HOSTING_COMPANY}"

# Sanitize users
#     https://www.debian.org/doc/debian-policy/ch-opersys.html#s9.2
#     https://www.debian.org/doc/manuals/securing-debian-howto/ch12.en.html#s-faq-os-users
# mcview /usr/share/doc/base-passwd/users-and-groups.html
tabs 20,+3,+8,+8,+20,+21,+8,+8,+8;sort -t':' -k3 -g /etc/passwd|tr ':' '\t';tabs -8
editor /etc/passwd
editor /etc/shadow
update-passwd -v --dry-run
#update-passwd -v

# Check user cron jobs
${D}/tools/catconf /etc/crontab /var/spool/cron/crontabs/*

