#!/bin/bash

set -e -x

# https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md
EXPECTED_SIGNATURE="$(wget -qO- "https://composer.github.io/installer.sig")"
php -r 'copy("https://getcomposer.org/installer", "composer-setup.php");'
ACTUAL_SIGNATURE="$(php -r 'echo hash_file("SHA384", "composer-setup.php");')"

if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]; then
    echo "ERROR: Invalid composer installer signature" 1>&2
    rm -f composer-setup.php
    exit 1
fi

php composer-setup.php --quiet
rm -f composer-setup.php
