#!/bin/bash

set -e -x

# Get pip
Pkg_install_quiet python3-dev python-dev
wget -nv "https://bootstrap.pypa.io/get-pip.py"
python3 get-pip.py
python2 get-pip.py

# @TODO Legacy list format
#mkdir -p ~/.config/pip
#echo -e "[list]\nformat=legacy" >> ~/.config/pip/pip.conf

# Fix overwritten six
pip2 uninstall -y six
# @nonDebian
Pkg_install_quiet --reinstall -t jessie-backports python-six
debsums -c python-six
