#!/bin/bash

set -e -x

# https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md
EXPECTED_SIGNATURE="$(wget -qO- "https://composer.github.io/installer.sig")"
php -r 'copy("https://getcomposer.org/installer", "composer-setup.php");'
ACTUAL_SIGNATURE="$(php -r 'echo hash_file("sha384", "composer-setup.php");')"

if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]; then
    echo "ERROR: Invalid composer installer signature" 1>&2
    rm -f composer-setup.php
    exit 1
fi

php composer-setup.php --quiet --install-dir /usr/local/bin --filename composer
rm -f composer-setup.php

# Display latest version number
#     wget -q -O- "https://getcomposer.org/versions" | jq -r '.stable[0].version'
