#!/bin/bash

set -e -x

# Aruba ExtraControl (serclient)
#     http://admin.dc3.arubacloud.hu/Manage/Serial/SerialManagement.aspx
#     https://github.com/pmcloud/ExtraControl

# Activation
# - Request ExtraControl activation
#     https://admin.dc3.arubacloud.hu/Manage/Serial/SerialActivation.aspx
# - "Switch off" the server
# - "Switch on" the server
# - Enter token

# Contains
# - Set log level
# - Comment out custom logrotate
# - Add logrotate configuration
# - Fix lintian errors
apt-get install -y aruba-serclient
