#!/bin/bash

set -e -x

Pkg_install_quiet chrony

editor /etc/chrony/chrony.conf
#     # OVH
#     server ntp.ovh.net offline iburst
#     # EZIT
#     server ntp.ezit.hu offline iburst
#
#     logchange 0.010
#     # Don't set hardware clock (RTC)
#     ##rtcsync
#     cmdport 0

service chrony restart
