#!/bin/bash

set -e -x

# https://packages.qa.debian.org/f/fail2ban.html

test -n "$IP"

Getpkg geoip-database-contrib
apt-get install -y geoip-bin python3-pyinotify fail2ban

for CONFIG in fail2ban.local jail.local; do
    cp -f security/fail2ban-conf/${CONFIG} /etc/fail2ban/
done
for FILTER in apache-combined.local apache-default.local apache-instant.local \
    courier-auth.local courier-smtp.local recidive.local; do
    cp -f security/fail2ban-conf/filter.d/${FILTER} /etc/fail2ban/filter.d/
done
for ACTION in cloudflare.local sendmail-geoip-lines.local; do
    cp -f security/fail2ban-conf/action.d/${ACTION} /etc/fail2ban/action.d/
done
sed -i -e "s|@@IP@@|${IP}|" /etc/fail2ban/jail.local
sed -i -e "s|@@SENDER@@|$(Data get-value package.fail2ban.sender "root")|" /etc/fail2ban/jail.local
# Already checked in debian-setup/openssh-server
sed -i -e "s|@@SSHPORT@@|$(Data get-value package.openssh-server.port "22")|" /etc/fail2ban/jail.local

# Apache may not be installed yet
service fail2ban stop
