#!/bin/bash

set -e -x

# https://packages.qa.debian.org/f/fail2ban.html

Getpkg geoip-database-contrib
apt-get install -y geoip-bin python3-pyinotify fail2ban

mc security/fail2ban-conf/ /etc/fail2ban/
# Config:     fail2ban.local
# Jails:      jail.local
# /filter.d:  apache-combined.local, apache-instant.local, courier-smtp.local, recidive.local
# /action.d:  cloudflare.local
#
# Search for "@@"

service fail2ban restart
