#!/bin/bash

# Host name ideas:
#     http://www.iata.org/publications/Pages/code-search.aspx
#     http://www.world-airport-codes.com/

set -e -x

H="$(Data get-value system.fqdn)"
test -n "$IP"

# Search for the old host name
grep -i -r "$(hostname)" /etc/ >/root/hostname-in-etc.log

# Set host name
hostname "$H"
echo "$H" >/etc/hostname
echo "$H" >/etc/mailname

# See `man hosts`
cp -f /etc/hosts /root/hosts.orig
cat >/etc/hosts <<EOF
127.0.0.1 localhost
127.0.1.1 localhost
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

# Original PTR=$(host "$IP" || true)
${IP} ${H} ${H%%.*}
EOF

# @TODO Support IPv6


# Check A and MX record
host -t A "$H"
host -t MX "$H"
# Optionally AAAA
if [ -n "$(Data get-value networking.inet6 "")" ]; then
    host -t AAAA "$H"
fi
# Check PTR (reverse DNS)
host -t PTR "$IP"
