#!/bin/bash

# Set A record and PTR record
# Consider: http://www.iata.org/publications/Pages/code-search.aspx
#           http://www.world-airport-codes.com/
read -r -e -p "Host name: " H

set -e -x

IP="$(ifconfig | sed -n -e '0,/^\s*inet addr:\([0-9\.]\+\)\b.*$/s//\1/p')"

# Search for the old host name
grep -i -r "$(hostname)" /etc/ > /root/hostname-in-etc.log

# Set host name
hostname "$H"
echo "$H" > /etc/hostname
echo "$H" > /etc/mailname

# See `man hosts`
cp -f /etc/hosts /root/hosts.orig
cat > /etc/hosts <<EOF
127.0.0.1 localhost
127.0.1.1 localhost
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

# Original PTR=$(host "$IP" || true)
${IP} ${H} ${H%%.*}
EOF

# Check A and MX record
host "$H"
# Check PTR (reverse DNS) record
host "$IP"
