#!/bin/bash

set -e -x

# @FIXME Order of rules: ESTABLISHED connection + fail2banned
#
#     -A INPUT -i lo -j ACCEPT
#     ??? -A INPUT -j fail2ban  <-- Move it up here
#     -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
#     -A INPUT -m conntrack --ctstate INVALID -j DROP
#     -A INPUT -j myattackers
#     -A INPUT -j myattackers-ipset
#     -A INPUT -j fail2ban

# Firewall rules

# http://inai.de/documents/Perfect_Ruleset.pdf
# Enable loopback traffic
iptables -A INPUT -i lo -j ACCEPT
ip6tables -A INPUT -i lo -j ACCEPT
# Enable statefull rules
iptables -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
ip6tables -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
# Drop invalid state packets
iptables -A INPUT -m conntrack --ctstate INVALID -j DROP
ip6tables -A INPUT -m conntrack --ctstate INVALID -j DROP

# IP range match (example)
#iptables -A INPUT -m iprange --src-range 10.10.96.255-10.10.97.14 -j REJECT

# Ban malicious hosts
Dinstall security/myattackers.sh
# Initialize iptables chain
myattackers.sh -i

# Deny traffic from known hostile networks
# @FIXME Depends on repo
(
    cd /usr/local/src/debian-server-tools/security/myattackers-ipsets/
    ./myattackers-ipsets-install.sh
)

# Save IPv4 iptables rules
iptables-save | grep -E -v '(:|\s)f2b-' | sed -e 's/ \[[0-9]*:[0-9]*\]$/ [0:0]/' >/etc/iptables/rules.v4

# Save IPv6 iptables rules
ip6tables-save | grep -E -v '(:|\s)f2b-' | sed -e 's/ \[[0-9]*:[0-9]*\]$/ [0:0]/' >/etc/iptables/rules.v6
