#!/bin/bash

set -e -x

Pkg_install_quiet mariadb-server mariadb-client
# @nonDebian
Pkg_install_quiet percona-xtrabackup

# @TODO Clone for percona-server-server
# @nonDebian
#Pkg_install_quiet percona-server-server-5.7 percona-server-client-5.7 percona-xtrabackup

# Disable the binary log
sed -i -e 's/^log_bin/#&/' /etc/mysql/my.cnf

Dinstall mysql/mysql-optimize.sh

# @TODO Config for repl? bin_log? xtrabackup?
