#!/bin/bash

set -e -x

mkdir /opt/drush
cd /opt/drush/

# https://github.com/drush-ops/drush/releases
composer require "drush/drush:7.*"
ln -s /opt/drush/vendor/bin/drush /usr/local/bin/drush

# Set up Drupal site
#     sudo -u SITE-USER -i
#     cd website/
#     drush dl drupal --drupal-project-rename=html
#     cd html/
#     drush site-install standard \
#         --db-url='mysql://DB-USER:DB-PASS@localhost/DB-NAME' \
#         --site-name=SITE-NAME --account-name=USER-NAME --account-pass=USER-PASS
#     drush --root=DOCUMENT-ROOT vset --yes file_private_path "PRIVATE-PATH"
#     drush --root=DOCUMENT-ROOT vset --yes file_temporary_path "UPLOAD-DIRECTORY"
#     drush --root=DOCUMENT-ROOT vset --yes cron_safe_threshold 0

# See /webserver/preload-cache.sh
