#!/bin/bash

CACHETOOL_URL="http://gordalina.github.io/cachetool/downloads/cachetool.phar"

set -e -x

wget -O /usr/local/bin/cachetool "$CACHETOOL_URL"
chmod +x /usr/local/bin/cachetool

# Usage
# cachetool --tmp-dir=/home/prg999/website/tmp --fcgi=/run/php/php7.0-fpm-prg999.sock opcache:status
