#!/bin/bash

set -e -x

# Aruba ExtraControl (serclient)
#     http://admin.dc3.arubacloud.hu/Manage/Serial/SerialManagement.aspx
(
    cd /root/dist-mod/
    wget -nv -nc "https://admin.dc3.arubacloud.hu/Installers/debian/aruba-serclient_0.01-1_all.deb"
    dpkg -i aruba-serclient_*_all.deb
)

# Set log level
# INFO 20, WARNING 30
echo -e "[LOG]\n#level = 20\nlevel = 30" >> /opt/serclient/serclient.ini

# Comment out
#     if getRestartGUID(remove=False) == None: rf.doRollover()
editor /opt/serclient/tools.py:159

# Update MD5 hash
md5sum /opt/serclient/tools.py
editor /var/lib/dpkg/info/aruba-serclient.md5sums

# Add logrotate
cat > /etc/logrotate.d/serclient <<"EOF"
/var/log/serclient.log {
    weekly
    rotate 15
    compress
    delaycompress
    notifempty
    create 640 root root
    postrotate
                if /etc/init.d/serclient status > /dev/null ; then \
                    /etc/init.d/serclient restart > /dev/null; \
                fi;
    endscript
}
EOF

# Aruba ExtraControl activation
#     https://admin.dc3.arubacloud.hu/Manage/Serial/SerialActivation.aspx
# - "Switch off" the server
# - "Switch on" the server
