#!/bin/bash

set -e -x

if [ "$WITHOUT_SYSTEMD" == "yes" ]; then
    # Remove systemd
    # http://without-systemd.org/wiki/index.php/How_to_remove_systemd_from_a_Debian_jessie/sid_installation
    if [ "$(dpkg-query --showformat="\${Status}" --show systemd 2> /dev/null)" == "install ok installed" ]; then
        apt-get install -y sysvinit-core sysvinit-utils bootlogd
        cp /usr/share/sysvinit/inittab /etc/inittab
        # Disable terminals 2-6
        # @TODO Consider /sbin/agetty
        sed -i -e '/^\([2-6]\):23:respawn:\/sbin\/getty 38400 tty\1$/d' /etc/inittab
        echo -e 'Package: *systemd*\nPin: origin ""\nPin-Priority: -1' > /etc/apt/preferences.d/systemd
        # Schedule removal of systemd
        echo "PATH=/usr/sbin:/usr/bin:/sbin:/bin
@reboot root apt-get purge -qq --auto-remove systemd > /dev/null;rm -f /etc/cron.d/withoutsystemd" > /etc/cron.d/withoutsystemd

        set +x
        echo
        echo "Are you sure you are able to log in? Port: $(netstat -n -a -t -p | grep -m 1 "/sshd\s*\$")"
        read -r -s -e -p "Hit Ctrl + D to reboot " || reboot
    fi
elif [ "$(dpkg-query --showformat="\${Status}" --show sysvinit-core 2> /dev/null)" == "install ok installed" ]; then
    # Remove SysVinit
    apt-get purge -qq sysvinit-core
    # Time synchronization
    timedatectl set-ntp 1
fi
