#!/bin/bash

set -e -x

if [ "$WITHOUT_SYSTEMD" == "yes" ]; then
    # Remove systemd
    # http://without-systemd.org/wiki/index.php/How_to_remove_systemd_from_a_Debian_jessie/sid_installation
    if [ "$(dpkg-query --showformat="\${Status}" --show systemd 2> /dev/null)" == "install ok installed" ]; then
        apt-get install -y sysvinit-core sysvinit-utils bootlogd
        cp /usr/share/sysvinit/inittab /etc/inittab
        echo -e 'Package: *systemd*\nPin: origin ""\nPin-Priority: -1' > /etc/apt/preferences.d/systemd
        # Schedule removal of systemd
        echo "PATH=/usr/sbin:/usr/bin:/sbin:/bin
@reboot root apt-get purge -qq -y --auto-remove systemd > /dev/null;rm -f /etc/cron.d/withoutsystemd" > /etc/cron.d/withoutsystemd
        echo "Log on this port: $(netstat -n -a -t -p | grep -m 1 "/sshd\s*\$")"
        read -r -s -e -p 'Ctrl + D to reboot ' || reboot
    fi
elif [ "$(dpkg-query --showformat="\${Status}" --show sysvinit-core 2> /dev/null)" == "install ok installed" ]; then
    # Remove SysVinit
    apt-get purge -qq -y sysvinit-core
fi
