#!/bin/bash

set -e -x

# µnscd
editor /etc/nscd.conf
#     enable-cache            hosts   yes
#     positive-time-to-live   hosts   60
#     negative-time-to-live   hosts   20

service unscd --full-restart
