# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "Actions"

on:  # yamllint disable-line rule:truthy
    pull_request: null
    push:
        branches:
        - "master"

permissions:
    contents: "read"

concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    actionlint:
        runs-on: "ubuntu-22.04"
        timeout-minutes: 1
        steps:
        -
            uses: "actions/checkout@v3"
        -
            uses: "docker://rhysd/actionlint:1.6.25"
            with:
                args: "-color -verbose -shellcheck ''"
