# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "Docs"

on:  # yamllint disable-line rule:truthy
    pull_request:
        paths:
        - "**/*.md"
        - "markdown-link-check.json"
    push:
        branches:
        - "master"
        paths:
        - "**/*.md"
        - "markdown-link-check.json"
    workflow_dispatch: null
# Add [skip ci] to commit message to skip CI.

permissions:
    contents: "read"

concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    markdown_link:
        name: "Markdown link"
        runs-on: "ubuntu-22.04"
        timeout-minutes: 10
        steps:
        -
            name: "Checkout repository"
            uses: "actions/checkout@v3"
        -
            name: "Get Yarn cache directory path"
            id: "yarn-cache-dir-path"
            run: |
                echo "dir=$(yarn cache dir)" >>"${GITHUB_OUTPUT}"
        -
            name: "Cache Yarn"
            uses: "actions/cache@v3"
            with:
                path: "${{ steps.yarn-cache-dir-path.outputs.dir }}"
                key: "${{ runner.os }}-yarn-markdown-link-check"
        -
            name: "Install markdown-link-check"
            run: "yarn global add markdown-link-check"
        -
            name: "Check Markdown links"
            run: |
                git ls-files -z -- '*\.md' \
                    | xargs -0 -- yarn run markdown-link-check -p -c markdown-link-check.json
