name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker://rhysd/actionlint:1.6.25
      with:
        args: "-color -shellcheck '' webserver/Continuous-integration-Continuous-delivery-commits.yml webserver/Continuous-integration-Continuous-delivery-docs.yml webserver/Continuous-integration-Continuous-delivery-front-end.yml webserver/Continuous-integration-Continuous-delivery-outdated.yml webserver/Continuous-integration-Continuous-delivery-spelling.yml webserver/Continuous-integration-Continuous-delivery-tag.yml webserver/Continuous-integration-Continuous-delivery-yaml.yml webserver/Continuous-integration-Continuous-delivery.yml"
