# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "Spelling"

on:  # yamllint disable-line rule:truthy
    pull_request: null
    push:
        branches:
        - "master"

permissions: {}  # yamllint disable-line rule:braces

concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    typos_check:
        name: "文A Typos check"
        runs-on: "ubuntu-24.04"
        timeout-minutes: 1
        steps:
        -
            name: "Checkout repository"
            uses: "actions/checkout@v5"
        -
            name: "Search for misspellings"
            uses: "crate-ci/typos@master"
